apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 2345 # Port on which the service will be available within the cluster
      protocol: TCP
      targetPort: 3001 # Must match the PORT of the container
