apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-todo-ingress
spec:
  rules:
  - host: ""
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: project-todo-svc
              port:
                number: 1234
