apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: exercises # namespace exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: log-writer
          image: yakovyakov/log-writer:4.0
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/shared-logs # log-writer write here
            - name: config-volume
              mountPath: /config
              readOnly: true
          envFrom:
            - configMapRef:
                name: log-writer-config
            - configMapRef:
                name: log-config
        - name: log-reader
          image: yakovyakov/log-reader:3.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: log-reader-config
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/shared-logs # log-reader read here
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-config
            items:
              - key: information.txt
                path: information.txt


