apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
  labels:
    type: local
    app: ping-pong-counter
spec:
  storageClassName: counter-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Multiple pods
  persistentVolumeReclaimPolicy: Retain # Retain data
  hostPath:
    path: /mnt/data/kube/counter
    type: DirectoryOrCreate    
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0