apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
    - port: 2345 # Port on which the service will be available within the cluster
      protocol: TCP
      targetPort: 80 # Must match the PORT of the container
