apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 2345 # Port on which the service will be available within the cluster
      protocol: TCP
      targetPort: 80 # Must match the PORT of the container
